Web_Test/Controllers/CountController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Test.Models.Logic;

namespace Web_Test.Controllers
{
    public class CountController:Controller
    {
        [HttpGet]
        public IActionResult Count()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Countlogic model)
        {
            ViewBag.Result = "您的結果值";
            if (ModelState.IsValid)
            {

                double result = model.Result;

                ViewBag.Result = result;
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult GetResult(int num1 , int num2 , string counts)
        {
           var countlogic = new Countlogic();
            {
                countlogic.Num1 = num1;
                countlogic.Num2 = num2;
                countlogic.Counts = counts;
            };
           

            return Json(countlogic.Result);
        }
       
    }
}

Web_Test/Views/Count/Count.cshtml
@using Web_Test.Models
@using Web_Test.Models.Logic
@model Countlogic
@{
    ViewData["Title"] = "計算機";
    Layout = "_Layout";
}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<div class="text-center">
    <h1>@ViewData["Title"]</h1>

    <div class="form-group">
        <form id="Countform"  method="post">
        <input asp-for="Num1" class="form-control" placeholder="請輸入數字">
        <p></p>
        <select id="Counts" name="Counts">
            <option value="addition">加</option>
            <option value="subtraction">減</option>
            <option value="multiplication">乘</option>
            <option value="division">除</option>
        </select>
        <p></p>
            <input asp-for="Num2" class="form-control" placeholder="請輸入數字" >
        </form>
        <p></p>
        <button id="CountData" type="button" class="btn btn-primary">計算</button>

    </div>
    
    <script>

        $(function () {
            $('#CountData').on('click', function () {
                var num1 = $('#Num1').val(); 
                var num2 = $('#Num2').val();
                var counts = $('#Counts').val();
                console.log(num1 , num2 );

                $.ajax({
                   
                    url: '@Url.Action("GetResult" , "Count")',
                    type: 'POST',
                    data: { num1: num1, num2: num2 , counts: counts },
                    success: function (data) {                      
                     
                        $('#resultValue').text(data);
                        
                        $('#resultDiv').show();
                    }
                    
                });
            });
        });
        
    </script>
    <p></p>
    <div id="resultDiv" style="display: none;">
        <h2> 結果: <span id="resultValue"></span></h2>
    </div>
 
    

</div>