Web_Test/Models/Student.cs
using System;
using System.Collections.Generic;

namespace Web_Test.Models;

public partial class Student
{
    public string Id { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string? ClassId { get; set; }

    public string Status { get; set; } = null!;

    public DateTime CreatTime { get; set; }

    public DateTime? UpdateTime { get; set; }
}

Web_Test/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Web_Test.Models.Logic;
namespace Web_Test.Controllers
{
    public class StudentController : Controller
    {
        [HttpGet]

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IndexPartial()
        {

            Student_Select student_Select = new Student_Select();

            var model = student_Select.GetStudents().OrderByDescending(o => o.UpdateTime).Take(10).ToList();

            return PartialView("_IndexPartial", model);
        }

        [HttpPost]
        public IActionResult SaveData(string id, string name)
        {

            Student_Select student_Select = new Student_Select();

            student_Select.SaveStudent(id, name);
            return Json("新增成功");

        }

        [HttpPost]

        public IActionResult UpdateData()
        {
            return Json("更新成功");
        }


        [HttpPost]
        public IActionResult DeleteData(string id)
        {

            Student_Select student_Select = new Student_Select();

            student_Select.DeleteStudent(id);

            return Json("刪除成功");

        }
    }
}

Web_Test/Views/Student/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "學生儲存";
}
@model List<Student>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<div class="text-center">
    <h1 class="display-4">新增學生資訊</h1>

    <label class="label">ID：</label> <input class="form-control" id="id" />
    <hr />
    <label class="label">NAME：</label><input class="form-control" id="name" />

    <a id="BtnSave" class="btn btn-success">新增</a>
</div>

<div class="text-center">
    <h1 class="display-4">編輯、刪除學生資訊</h1>
</div>

<div id="Div_List" class="container">

</div>

<script>
    $(function () {
        LoadList();

        $('#BtnSave').on('click', function () {
            $.ajax({
                url: '@Url.Action("SaveData", "Student")',
                data: { id: $('#id').val(), name: $('#name').val() },
                method: 'post'
            }).done(function (res) {
                alert(res);
                
                LoadList();
            });
        })
    })


    function LoadList() {
      
        $.ajax({
            url: '@Url.Action("IndexPartial", "Student")',
            method: 'post'
        }).done(function (res) {
            console.log(res);  
            $('#Div_List').html(res);
        });
    }

    function DeleteData(id) {
        if (confirm('確定刪除學號${id}的資料?'))
        { 
           $ajax({
               url:'@Url.Action("DeleteData" , "Student")',
               data: {Id: id},
               method :'post'
           }).done(function (res) {

               alert(res);
               LoadList();
           })
        
        
        }
    
    
    }

</script>

Web_Test/Views/Student/_IndexPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Web_Test.Models.Logic
@model List<Student>

@{
    // 因為是附加到主頁, 所以不需要任何的base(基底)頁面
    Layout = null;
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>更新時間</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@(item.UpdateTime.HasValue ? item.UpdateTime.Value.ToString("yyyy/MM/dd") : "-")</td>
                <td><a class="btn btn-danger" name="BtnDelete" data-id="@item.Id">刪除</a></td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(function () {
        // 這邊因為此處都會重新產生, 需要將刪除綁定在這
        $('a[name="BtnDelete"]').on('click', function () {
            var id = $(this).data('id');
            DeleteData(id); // 此方法寫在主頁
        })
    })
</script>